name: Continuous Integration

on: 
  push_request:
    branches: [ master ]


jobs: 
  test_push_request:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2   
      - uses: actions/setup-node@v1
        with:
          node_verison: 14
        run: npm install
        run: npm test  